export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';

export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_USER_ERROR = 'SIGNOUT_ERROR';

export const ADD_WATCHA_SUCCESS = 'ADD_WATCHA_SUCCESS';
export const ADD_WATCHA_ERROR = 'ADD_WATCHA_ERROR';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
