export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ADD_WATCHA_SUCCESS = 'ADD_WATCHA_SUCCESS';
export const ADD_WATCHA_ERROR = 'ADD_WATCHA_ERROR';
export const RESET_WATCHA = 'RESET_WATCHA';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS';
export const UPDATE_CHAT_ERROR = 'UPDATE_CHAT_ERROR';
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS';
export const GET_CHAT_ERROR = 'GET_CHAT_ERROR';
